// <auto-generated />
namespace LO54_Projet.Repository.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AfterMerge1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfterMerge1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905061904429_AfterMerge1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
